### PR TITLE
Split google-cloud-provider to support independent service-specific providers

### PR DESCRIPTION
**Pull request by bmhatfield**
Currently, GoogleCloudProvider as structured will always build all internal targets and dependencies.

As GoogleCloudProvider grows, this will pose a challenge as attempting to use **any** service it supports will require that folks depend on and compile **all** services that it supports.

To better manage adding providers for individual services, this restructures GoogleCloudProvider to have multiple targets:

Core, which includes the base provider definitions, OAuth, and Credentials.

Storage, which includes the google cloud storage provider.

This PR also includes a refactor moving `withToken` to `OAuthRefreshable`, rather than as part of `StorageRequest` (so that it can be re-used by other providers) and moves credential path discovery to `OAuthCredentialLoader` rather than `StorageClient` (again, for re-use).

TODO:

- [x] Restructure code paths so individual targets can be published as separate libraries
- [x] Abstract some OAuth behaviors from `Storage`
- [x] Remove `Provider` from all names
- [ ] Update Readme.md files with updated instructions for import and configure
- [ ] Re-structure tests for updated structure

### CODE REVIEW

**Comment by bmhatfield** [comment]
Please note: This is currently somewhat of a work-in-progress. We're working on adding a second provider now, so this PR may update as we discover more places where refactoring is needed.

**Comment by Andrewangeta** [comment]
This is a good idea 👍🏽

**Review by Andrewangeta — CHANGES_REQUESTED** [review]
We can actually remove the ProviderCore Extension. I was meaning to remove it at some point. Because as fsr as style goes for Vapor providers the product name is enough to be the module name. E.g `import Stripe`
`import GoogleCloud`

**Comment by bmhatfield** [comment]
@Andrewangeta I agree, that looks super nice. Pushed an update. I do need to keep the `Core` part of that name, as it distinguishes the `Core` code from the `Storage` or `KMS` or `PubSub` parts.

Please note - I would still consider this in WIP state - we haven't gone and updated the tests for this yet, eg.

However if you have other feedback we're all ears :-)

**Pull request closed without merging**
