### PR TITLE
Add implementation for Google Key Management Service - decrypt

### PR DESCRIPTION
**Pull request by popaaaandrei**
The implementation follows the lines of CloudStorage implementation, but I guess we could generalize parts of the code, at least unifying some of the network requests. For now, it's only the decrypt functionality. If people need it, I can easily implement create/encrypt as well.

### CODE REVIEW

**Review by Andrewangeta — COMMENTED** [review]
I’ll have sometime this Tuesday to look over it some more. Out of country atm. Only thing so far at a quick glance, is just some formatting. Like preferring to use the MARK: - Whatever over the triple liner comment box. Just to keep it consistent and follow swift styles for easier Xcode support.

**Comment by popaaaandrei** [comment]
Do you also think we can unify some of the basic network requests? If more APIs will be implemented maybe we need to formalize some implementation guidelines and generalize as much as possible

**Comment by Andrewangeta** [comment]
@popaaaandrei I don't necessarily think so, Since all of these separate Clients/API's are implemented on their own, and some of the requests vary slightly, I think for now it should be fine to have them separated. Unless you have a clean approach for unifying right now?

**Comment by popaaaandrei** [comment]
I think that we can for starters unify `private func withToken<F>` and `private func _send` and make a common error model rather than creating separate Error implementations for each use-case. What if we have 20 APIs implemented? Should we have one Error implementation or 20?

**Comment by Andrewangeta** [comment]
@popaaaandrei the only issue I see with `_send` is the custom error model that’s decoded is different per API. The withToken sure but having it in one spot could help. Maybe add it in the provider as a global func? Not clear just yet.

**Comment by popaaaandrei** [comment]
Just some thoughts: we could supply the error type that needs to be decoded as a parameter. All the Google APIs return different types of errors?

**Comment by popaaaandrei** [comment]
Tell me if you still want to merge this or should I close it

**Comment by popaaaandrei** [comment]
@Andrewangeta what shall we do with this one?
I guess I need to rebase and add KMS from scratch, but I don't have either Catalina nor Swift 5.2 / Vapor 4.

**Comment by Andrewangeta** [comment]
@popaaaandrei I think we can actually move this to GoogleCloudKit for the base implementation. That way the vapor 4 provider can just use the extension the same way cloud storage uses it. What do you think?

**Pull request closed without merging**
